version: 2.1 # CircleCI version
orbs:
  aws-s3: circleci/aws-s3@2.0.0
jobs:
  build:
    machine: true # Use a Linux VM instead of docker environment
    working_directory: ~/repo # Default working directory, where your project will be cloned
    steps:
      - checkout
      - run: docker-compose up --build
      - run: cp ./src/.env.example ./src/.env
      - run: docker-compose run --rm composer install
      - run: docker-compose run --rm key:generate
      - run: docker-compose run --rm migrate:refresh --seed
      - run: docker-compose run --rm php ./vendor/bin/phpunit

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build